data_ingestion:
  seed: 42
  test_size: 0.225

feature_engineering:
  bow_max_features: 100

model_training:
  estimator:
    criterion: "gini"
    splitter: "best"
    max_depth: 5
    min_samples_split: 5
    min_samples_leaf: 2
    estimator_max_features: 0.80
    estimator_random_state: 42

  bagging:
    n_estimators: 10
    max_samples: 0.80
    bagging_max_features: 0.80
    bootstrap: False
    bootstrap_features: False
    oob_score: False
    warm_start: False
    bagging_random_state: 42
    verbose: 1
